input {
  kafka {
    bootstrap_servers => "172.28.0.6:9092"
    topics => ["user_login", "payment", "item_view"]
    codec => json
    group_id => "logstash-group"
    auto_offset_reset => "earliest"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "kafka-events-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
