input {
  file {
    path => "/usr/share/logstash/nginx/access.log"  # 👈 Новый путь
    start_position => "beginning"
    sincedb_path => "/dev/null"
    tags => ["nginx-access"]
  }
}

filter {
  grok {
    match => { "message" => "%{IPORHOST:clientip} - %{USER:ident} \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{URIPATHPARAM:request} HTTP/%{NUMBER:httpversion}\" %{NUMBER:response} %{NUMBER:bytes} \"%{DATA:referrer}\" \"%{DATA:agent}\"" }
  }
  date {
    match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
    target => "@timestamp"
  }
  mutate {
    remove_field => [ "timestamp", "ident", "message" ]
    convert => [ "bytes", "integer" ]
    convert => [ "response", "integer" ]
  }
  useragent {
    source => "agent"
    target => "user_agent"
  }
}

output {
  if "nginx-access" in [tags] {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "nginx-logs-%{+YYYY.MM.dd}"
    }
    stdout { codec => rubydebug }
  }
}
